ipc = on

wallpaper {
    monitor = DP-1
    path = /home/joao/Pictures/Wallpapers/h/SnowMountain.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/joao/Pictures/Wallpapers/v/NeonPinkBridge.jpg
    fit_mode = cover
}
