###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nemo
$menu = wofi --show drun "Apps" --width 400 --height 500 --allow-images
$browser = firefox
$clipboard = cliphist list | wofi --dmenu | cliphist decode | wl-copy
